name: "Laravel 7"
on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.3", "7.4", "8.0" ]
                laravel: [ "7.0" ]

        name: PHP ${{ matrix.php }}

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: default
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup Redis
                uses: zhulik/redis-action@1.1.0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, pdo_mysql
                    coverage: none

            -   name: Install dependencies
                run: composer require --dev laravel/framework:^${{ matrix.laravel }} doctrine/dbal:^2.6

            -   name: Execute tests
                run: sudo vendor/bin/phpunit
                env:
                    MYSQL_HOST: 127.0.0.1
